version: "3.8"
services:
  nginx:
    image: nginx:alpine
    depends_on:
      - consumers
    volumes:
      - ./SampleRepo/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  consumers:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - rabbit_exchange=teamsquad.eventBus
      - rabbit_event_listen=io.test.testservice
      - rabbit_host=rabbitmq
      - rabbit_port=5672
      - rabbit_user=guest
      - rabbit_pass=guest
    volumes:
      - .:/app

  amqp2fcgi:
    image: usregistry.vtsmedia.com/iflmedia/amqp2fcgi:1.0.9
    ports:
      - "1111:1111"
    depends_on:
      - consumers
      - rabbitmq
    environment:
      - AMQP2FCGI_WORKERS=1
      - AMQP2FCGI_FCGI_ENDPOINT=consumers:9000
      - AMQP2FCGI_FCGI_FILE=/app/SampleRepo/index.php
      - AMQP2FCGI_LOGGER_DEVELOPMENT=true
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./SampleRepo/data/rabbitmq:/var/lib/rabbitmq:rw
      - ./SampleRepo/config/rabbit/definitions.json:/opt/definitions.json:ro
      - ./SampleRepo/config/rabbit/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
