# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: CI
permissions:
  contents: read

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'CHANGELOG.md'
      - 'CODEOWNERS'
      - 'SECURITY.md'
      - 'docs/**'
      - '.gitignore'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'CHANGELOG.md'
      - 'CODEOWNERS'
      - 'SECURITY.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  coding-guidelines:
    name: Coding Guidelines
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run friendsofphp/php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --show-progress=dots --using-cache=no --verbose

  type-checker:
    name: Type Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Psalm
        run: ./vendor/bin/psalm --config=psalm.xml --no-progress --shepherd --show-info=false --stats

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze -c phpstan.neon

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        php: [ '8.0' ]
    name: Tests on PHP ${{ matrix.php }} - ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --no-ansi --no-progress

      - name: Run composer dump autoload optimised
        run: composer dump-autoload --optimize --classmap-authoritative

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

      - name: Generate coverage report
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
        if: matrix.operating-system == 'ubuntu-latest'

      - name: Post Coverage
        uses: codecov/codecov-action@v3
        if: matrix.operating-system == 'ubuntu-latest'
